SELECT
	STUDENT_ID,
    TEST_ID,
    GRADE_ID,
    PERIOD_ID,
    TEST_DATE,
    IF(METREQ_01 = 1, '+', '-') AS METREQ,
    IF(TEST_DATE = LAST_DATE AND b.METREQ_01 = 0, 1, 0) AS IN_PROGRESS
FROM exam AS a

LEFT JOIN
    (SELECT
		STUDENT_ID,
        GRADE_ID,
        PERIOD_ID,
        MAX(PASS_FAIL) AS METREQ_01,
        MAX(TEST_DATE) AS LAST_DATE
	FROM exam
	GROUP BY STUDENT_ID, GRADE_ID, PERIOD_ID) AS b
USING(STUDENT_ID, GRADE_ID, PERIOD_ID) 